### ISSUE TITLE
[TECH-DEBT] Test-isolation leak forces test_healthz_envelopes + test_readiness off CI

### ISSUE THREAD

**Issue by yurisa2** [PetroSa2/petrosa-tradeengine#444]
# [TECH-DEBT] Test-isolation leak forces test_healthz_envelopes + test_readiness off CI

## Problem

`tests/test_healthz_envelopes.py` and `tests/test_readiness.py` pass in isolation but **fail in the full-suite run order** with:

```
TypeError: object MagicMock can't be used in 'await' expression
```

Reproduced locally (with `pytest -p no:randomly`):

```
========== 10 failed, 1002 passed, 10 skipped, 20 warnings in 52.45s ===========
FAILED tests/test_healthz_envelopes.py::test_healthz_envelopes_returns_unconfigured_when_no_fetcher
FAILED tests/test_healthz_envelopes.py::test_healthz_envelopes_surfaces_cached_entries
FAILED tests/test_readiness.py::TestReadinessComponentFailureLogging::test_dispatcher_failure_includes_component_name
… (8 more readiness tests fail the same way)
```

An earlier test in the order is leaving a `MagicMock` bound where the FastAPI lifespan / route handler then tries to `await` it. The exact culprit needs investigation — candidates are anything that patches `app.state`, the OTel-instrumented route layer, or the envelope-fetcher / readiness singletons without proper teardown.

## How it got here

Originally surfaced as a different symptom: `TypeError: Client.__init__() got an unexpected keyword argument 'app'` — that one was the starlette 0.45 ↔ httpx 0.28 mismatch in `TestClient.__init__`. After bypassing that via `httpx.ASGITransport` (see PR #443), the deeper await-on-MagicMock leak became visible. CI has been red on `main` since 2026-06-01 because of this (runs 26766026232, 26766104099).

## Workaround currently in place (PR #443)

`.github/workflows/ci-checks.yml` adds both files to the `pytest-extra-args` ignore list — matching the existing pattern that already ignores `test_api.py`, `test_cio_state.py`, `test_trading_config_rollback.py`, `test_span_attributes.py`, and 3 other isolation-broken files. **The tests are not deleted** — they still pass in isolation.

### AC1 — Identify the leak source
- [ ] `pytest -p no:randomly tests/` reproduces the failure deterministically; bisect (or use `pytest --basetemp + plugin order`) to identify the specific earlier test(s) that leave a `MagicMock` in a place subsequent FastAPI route handlers `await`.
- [ ] Add a brief postmortem of what was leaked (which module-level singleton / `app.state` / OTel layer) to the PR description.

### AC2 — Fix the leak at the source
- [ ] The offending test's teardown (or its fixture's `yield`-after block) restores the patched object.
- [ ] The two impacted files run cleanly inside the full suite without `--ignore`.

### AC3 — Restore the suite
- [ ] Remove `--ignore=tests/test_healthz_envelopes.py` and `--ignore=tests/test_readiness.py` from `.github/workflows/ci-checks.yml`.
- [ ] CI is green on `main`.

### AC4 — Guard against regression
- [ ] Add an autouse fixture (or a conftest hook) that snapshots & restores the module-level singletons read by `/healthz/envelopes` and `/readiness` between tests, so a future leak fails loudly at the offending test instead of silently breaking these two suites.

## Technical anchors

- `tests/test_healthz_envelopes.py` — last 2 tests passing in isolation.
- `tests/test_readiness.py` — `TestReadinessAggregation` + `TestReadinessComponentFailureLogging` all fail in-order.
- `tradeengine/api.py:482` — `/healthz/envelopes` route handler.
- `tradeengine/services/envelope_fetcher.py:_envelope_fetcher` — the module-level singleton.
- Workaround commit: `3f94ef0` on `main` (`ci(healthz): ignore … pending isolation fix`).
- See also memory `project_otel_test_isolation_leak_ta_analysis.md` — same family of bug in bot-ta-analysis.

## Estimation

- **Priority:** P2 (CI was already red on main for a related reason; the ignore-list workaround keeps merge gates functional)
- **Size:** M
- **Type:** Tech debt / test infrastructure

## Related

- #442 — the ticket whose PR (#443) added the ignore-list workaround.
- petrosa-tradeengine PR #443 — `fix(distributed_lock): lazy reconnect…` (where this surfaced).

**Comment by yurisa2** [comment]
Promoted Backlog→Ready (PM dependency-triage pass 2026-06-04): no unresolved upstream code dependencies blocking pickup.

**Comment by yurisa2** [comment]
### MemPalace pre-flight report

**Dispatcher:** ticket-orchestrator
**Ticket:** PetroSa2/petrosa-tradeengine#444 — "[TECH-DEBT] Test-isolation leak forces test_healthz_envelopes + test_readiness off CI"
**Affected service phrase:** "tradeengine test isolation MagicMock leak healthz readiness"

**Searches run**
- semantic search on title — 5 hits, top: petrosa/technical (CIO context gap audit MagicMock — unrelated code path, similarity 0.51)
- kg query on `PetroSa2/petrosa-tradeengine#444` — 1 triple: `follow_up_of PetroSa2/petrosa-tradeengine#442`
- tunnel discovery (petrosa↔petrosa) — 2 rooms (architecture, diary); no test-isolation specific tunnel found

**Key findings**
- #444 is a follow-up of #442 (lazy MongoDB reconnect) — the ignore-list workaround was added in PR #443 as part of that fix
- Memory `project_otel_test_isolation_leak_ta_analysis.md` documents a same-family leak in bot-ta-analysis (OTel SDK disabled popping process-wide on import); similar teardown-failure root cause but different service
- No prior MemPalace drawer records a fix attempt for this specific tradeengine leak — this is new work
- Workaround currently in place: `.github/workflows/ci-checks.yml` ignores `tests/test_healthz_envelopes.py` and `tests/test_readiness.py`
- The leak leaves a `MagicMock` where FastAPI route handlers try to `await` it — candidates are `app.state`, envelope-fetcher singleton, or readiness singletons without proper teardown

**Decision impact**
- No architectural constraint from memory changes the approach; will investigate `tradeengine/services/envelope_fetcher.py` singleton + conftest fixtures for the offending patch teardown gap

**Repo-drift flag:** no (ticket filed in implementing repo PetroSa2/petrosa-tradeengine)

**MemPalace availability:** OK

**Comment by yurisa2** [comment]
### BMAD lifecycle: work started

Work on this ticket has started. Project board status: **In progress**.

**Comment by yurisa2** [comment]
### BMAD lifecycle: ready for review

Pull request: https://github.com/PetroSa2/petrosa-tradeengine/pull/455

Project board status: **In review**.

**Comment by yurisa2** [comment]
### BMAD lifecycle: merge complete

The change has been merged. PR: https://github.com/PetroSa2/petrosa-tradeengine/pull/455

Project board status: **Done**.

**Comment by yurisa2** [comment]
### BMAD lifecycle: finalization complete

AC1: root-caused sys.modules collection-time leak; AC2: removed module-level mock from 3 test files; AC3: removed --ignore workaround from ci-checks.yml; AC4: _restore_api_module_isolation autouse fixture with proactive repair. 1381 passed locally, CI green.
